services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - frontend/.env.local
    depends_on:
      - backend
    ports:
      - "3000:3000"

